### ISSUE TITLE
Failing when running /usr/share/varnish-plus/vmodtool.py on varnisn-plus-6

### ISSUE THREAD

**Issue by auduny** [Dridi/libvmod-querystring#40]
```
config.status: executing libtool commands

	==== libvmod-querystring 1.0.5 ====

	varnish:      6.0.0r2
	prefix:       /usr
	vmoddir:      /usr/lib64/varnish-plus/vmods

	compiler:     gcc -std=gnu99
	cflags:       -g -O2
	ldflags:

	--enable-silent-rules=
	--enable-warnings=no
	--enable-docs=no
	--enable-lcov=no

Making install in src
make[1]: Entering directory `/usr/local/src/vmod-querystring-1.0.5/src'
/usr/bin/python /usr/share/varnish-plus/vmodtool.py -o vcc_querystring_if ./vmod_querystring.vcc
While parsing line:
	 Synopsis manual

WARNING: Unknown stanze $Synopsis manual

Traceback (most recent call last):
  File "/usr/share/varnish-plus/vmodtool.py", line 1089, in <module>
    runmain(i_vcc, opts.rstdir, opts.output)
  File "/usr/share/varnish-plus/vmodtool.py", line 1042, in runmain
    v.parse()
  File "/usr/share/varnish-plus/vmodtool.py", line 857, in parse
    m([c[0], " ".join(c[1:])], ss[i:].split('\n'), self)
TypeError: 'NoneType' object is not callable
make[1]: *** [vcc_querystring_if.c] Error 1
make[1]: Leaving directory `/usr/local/src/vmod-querystring-1.0.5/src'
make: *** [install-recursive] Error 1
```

**Comment by Dridi** [comment]
Hello,

Your issue flew under my radar and I'm only noticing it now after releasing vmod-querystring 1.0.6 and 2.0, apologies. Unfortunately I'm not supporting Varnish Plus here, although it should work seamlessly. Does it still happen with a recent Varnish Plus release?

If yes, you can try this:

- copy `vmodtool.py` from Varnish Cache 6.0.0 somewhere on your system
- run `make VMODTOOL=/path/to/your/vmodtool.py`

I wouldn't expect the latest VCP 6 release to be a problem, it just worked for me.

**Comment by Dridi** [comment]
ETIMEDOUT
